name: Auto Deploy to Amazon EC2

on:
  push:
    branches:
      - main
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/heads/release/') && 'release' || 'production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 & Deploy with Rollback
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            echo "Starting deployment on ${{ secrets.DOMAIN }}"

            APP_DIR="${{ secrets.EC2_APP_DIR }}"
            PM2_APP="${{ secrets.PM2_APP_NAME }}"
            APP_PORT="${{ secrets.APP_PORT }}"
            DOMAIN="${{ secrets.DOMAIN }}"
            WWW_DOMAIN="${{ secrets.WWW_DOMAIN }}"

            cd $APP_DIR

            CURRENT_COMMIT=$(git rev-parse HEAD)
            echo $CURRENT_COMMIT > ~/.last_good_commit
            echo "Saved current commit: $CURRENT_COMMIT"

            git fetch origin
            git reset --hard origin/${{ github.ref_name }}

            npm ci --omit=dev

            pm2 stop $PM2_APP || true
            pm2 start src/server.js --name $PM2_APP -- -p $APP_PORT
            sleep 5

            if ! curl -fs "http://localhost:$APP_PORT/health" > /dev/null; then
              echo "Health check failed. Rolling back..."
              git reset --hard $(cat ~/.last_good_commit)
              npm ci --omit=dev
              pm2 stop $PM2_APP || true
              pm2 start src/server.js --name $PM2_APP -- -p $APP_PORT
              echo "Rolled back to last known good commit."
              exit 1
            fi

            echo "New version is healthy"

            sudo bash -c "cat > /etc/nginx/conf.d/${DOMAIN}.conf" <<EOF
            server {
                listen 80;
                server_name $DOMAIN $WWW_DOMAIN;

                location /.well-known/acme-challenge/ {
                    root /var/www/certbot;
                }

                location / {
                    return 301 https://$DOMAIN\$request_uri;
                }
            }

            server {
                listen 443 ssl;
                server_name $WWW_DOMAIN;
                
                ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

                return 301 https://$DOMAIN\$request_uri;
            }

            server {
                listen 443 ssl;
                server_name $DOMAIN;

                ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
                ssl_protocols TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers on;

                location / {
                    proxy_pass http://localhost:$APP_PORT;
                    proxy_http_version 1.1;
                    proxy_cache_bypass $http_upgrade;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }
            EOF

            sudo nginx -t && sudo systemctl reload nginx

            sudo mkdir -p /var/www/certbot
            sudo certbot --nginx -d $DOMAIN -d $WWW_DOMAIN --non-interactive --agree-tos -m admin@$DOMAIN || true
            sudo systemctl reload nginx

            echo "EC2 Deployment completed successfully for $DOMAIN"
