name: Unit Testing

on:
  push:
    branches:
      - main
      - release/*
      - develop

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js runtime
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        env:
          NODE_ENV: test
          PORT: ${{ secrets.PORT }}
          RATE_LIMITER_WINDOW_SEC: ${{ vars.RATE_LIMITER_WINDOW_SEC }}
          RATE_LIMITER_MAX_REQ: ${{ vars.RATE_LIMITER_MAX_REQ }}
          DATABASE_URL: postgres://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ vars.POSTGRES_DB }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          REDIS_URL: redis://@localhost:6379/0
          NODEMAILER_SENDER: ${{ secrets.NODEMAILER_SENDER }}
          NODEMAILER_USER: ${{ secrets.NODEMAILER_USER }}
          NODEMAILER_PASS: ${{ secrets.NODEMAILER_PASS }}
          NODEMAILER_HOST: ${{ secrets.NODEMAILER_HOST }}
          NODEMAILER_PORT: ${{ secrets.NODEMAILER_PORT }}
          S3_ENDPOINT: http://localhost:9000
          S3_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_KEY }}
          S3_TEST_BUCKET_NAME: ${{ vars.S3_TEST_BUCKET_NAME }}
          S3_REGION: ${{ vars.S3_REGION }}
        run: npm run -s test:unit:clean